server:
  port: 8081

spring:
  application:
    name: HuangxxMIS11

  datasource:
    url: jdbc:postgresql://localhost:15432/huangxx_mis11
    username: gaussdb
    password: Huangxx@123
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  sql:
    init:
      mode: never

logging:
  level:
    com.huangxx.mis: info
